### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by martindurant** [conda-forge/intake-feedstock#1]
A little surprised to see this appear here, @ocefpaf !
Thanks for putting the effort in.

You should know that, as things stand, the intake channel will continue to have a rapid release cycle reflecting the current state of development, and pypi releases (which will trigger updates here) relatively rarer. Do you think it would be worthwhile to move the whole set of packages to conda-forge at this point? I would appreciate being added as maintainer.

**Comment by ocefpaf** [comment]
> A little surprised to see this appear here, @ocefpaf !
> Thanks for putting the effort in.

I added this after users requests. They were trying to run demos they saw online.

> You should know that, as things stand, the intake channel will continue to have a rapid release cycle reflecting the current state of development, and pypi releases (which will trigger updates here) relatively rarer.

I would like to persuade you to make more PyPI stable releases insted b/c [I'm 100% RERO](https://en.wikipedia.org/wiki/Release_early,_release_often). However, I don't really have stake here and I don't use latest dev releases at all. I guess that only people trying to reproduce the demos they see online do and most of the packages I add here is to try to easy their pain.

> Do you think it would be worthwhile to move the whole set of packages to conda-forge at this point?

Not sure about what you mean by "the whole set." If you mean dev releases we can do those via a `label`.

> I would appreciate being added as maintainer.

Sure. All that is needed is a PR adding your [GitHub handle here](https://github.com/conda-forge/intake-feedstock/blob/master/recipe/meta.yaml#L72-L74) and, once merged, you'll have full access to this feedstock.

**Comment by martindurant** [comment]
> Not sure about what you mean by "the whole set." 

https://anaconda.org/intake/repo , mostly intake plugins. Probably the more specific data packages can stay there forever.

**Comment by ocefpaf** [comment]
> [anaconda.org/intake/repo](https://anaconda.org/intake/repo) , mostly intake plugins. Probably the more specific data packages can stay there forever.

Ah OK. I guess that depends on what users want. IMO I would make `conda-forge` the canonical third party community channel to be used along side `defaults`. But, as a conda-forge core member, I'm bisaed :grimacing:

**Comment by rsignell-usgs** [comment]
@martindurant, I love the idea of having the latest intake available on conda-forge.  It makes integration with other packages much easier.   

There are quite a few packages that release early and often on conda-forge in a fashion that apparently put little burden on the conda-forge maintainers.  Check this these [recent boto releases](https://github.com/conda-forge/boto3-feedstock/pulls?q=is%3Apr+is%3Aclosed), for example!

**Comment by martindurant** [comment]
OK, I'll put it on my (extending) to-do list.
